// <auto-generated />
namespace WebApi2Book.Data.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201707062155218_initial add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
